<?xml version="1.0" encoding="utf-8"?><Database Name="dztz" Class="DataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=dztz;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dztzConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LedgerNodeItem" Member="LedgerNodeItems">
    <Type Name="LedgerNodeItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LedgerNodeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LedgerNodeName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ModifyTime" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TemplateValue" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.LedgerNode" Member="LedgerNodes">
    <Type Name="LedgerNode">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LedgerNodeType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LedgerNodeName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Station" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ModifyTime" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Reserved1" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Reserved2" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TemplateFileName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TemplateContent" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.AccessLevel" Member="AccessLevels">
    <Type Name="AccessLevel">
      <Column Name="ALName" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ALValue" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Department" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="LoginName" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="UserPassword" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePhone" Type="System.String" DbType="NChar(32)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="AccessRight" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LoginTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastLoginTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LoginCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>